name: Checking and pushing the files
on: push
jobs:
  flake8-lint:
    name: Flake8 check
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Flake8 lint check
        uses: py-actions/flake8@v2

  editorconfig-check:
    name: EditorConfig check
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

  makrdown-checker:
    name: Markdown check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npx markdown-cli *.md

  run-unit-tests:
    name: Run python unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.13
          architecture: x64
      - name: Install requirements
        run: pip3 install -r src/requirements.txt
      - name: Run unit tests
        run: python3 -m unittest src/app_test.py

  build-and-push:
    name: Build and push the docker container
    needs: [ flake8-lint, editorconfig-check, makrdown-checker, run-unit-tests ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:latest
